connection:
  info:
    ip: 192.168.1.176
    port: '5000'
    tls_config:
      enable: false
  name: FlaskConnection
  path: ibmfl.connection.flask_connection
  sync: false
data:
  info:
    npz_file: /home/trevormaxjs/Documents/Engineering/Research/ibmfl/examples/datasets/mnist.npz
  name: MnistKerasDataHandler
  path: ibmfl.util.data_handlers.mnist_keras_data_handler
fusion:
  name: CoordinateMedianFusionHandler
  path: ibmfl.aggregator.fusion.coordinate_median_fusion_handler
hyperparams:
  global:
    max_timeout: 50
    num_parties: 90
    perc_quorum: 0.5
    rounds: 20
    termination_accuracy: 0.9999
  local:
    optimizer:
      lr: 0.01
    training:
      epochs: 10
protocol_handler:
  name: ProtoHandler
  path: ibmfl.aggregator.protohandler.proto_handler
