experiments:
  agg_machine: local0
  isLocalRun: 'false'
  local_ibmfl_dir: /home/trevormaxjs/Documents/Engineering/Research/ibmfl
  local_staging_dir: /home/trevormaxjs/Documents/Engineering/Research
  n_parties: 90
  n_rounds: 20
  n_trials: 1
  party_machines:
  - popdesk0
  - popdesk1
  - popdesk2
  - popdesk3
  - popdesk4
  - popdesk5
  - popdesk6
  - popdesk7
  - popdesk8
  - popdesk9
  - worktop10
  - worktop11
  - worktop12
  - worktop13
  - worktop14
  - worktop15
  - worktop16
  - worktop17
  - worktop18
  - worktop19
  - worktop20
  - worktop21
  - worktop22
  - worktop23
  - worktop24
  - worktop25
  - worktop26
  - worktop27
  - worktop28
  - worktop29
  - worktop30
  - worktop31
  - worktop32
  - worktop33
  - worktop34
  - worktop35
  - worktop36
  - worktop37
  - worktop38
  - worktop39
  - worktop40
  - worktop41
  - worktop42
  - worktop43
  - worktop44
  - worktop45
  - worktop46
  - worktop47
  - worktop48
  - worktop49
  - schooltop50
  - schooltop51
  - schooltop52
  - schooltop53
  - schooltop54
  - schooltop55
  - schooltop56
  - schooltop57
  - schooltop58
  - schooltop59
  - schooltop60
  - schooltop61
  - schooltop62
  - schooltop63
  - schooltop64
  - schooltop65
  - schooltop66
  - schooltop67
  - schooltop68
  - schooltop69
  - keegdesk70
  - keegdesk71
  - keegdesk72
  - keegdesk73
  - keegdesk74
  - keegdesk75
  - keegdesk76
  - keegdesk77
  - keegdesk78
  - keegdesk79
  - keegdesk80
  - keegdesk81
  - keegdesk82
  - keegdesk83
  - keegdesk84
  - keegdesk85
  - keegdesk86
  - keegdesk87
  - keegdesk88
  - keegdesk89
  postproc_fn: gen_reward_vs_time_plots
  postproc_x_key: post_train:ts
  postproc_y_keys:
  - post_train:eval:loss
  - post_train:eval:acc
  shuffle_party_machines: 'false'
isLocalRun: 'false'
machines:
  default:
    ibmfl_dir: /home/trevormaxjs/Documents/Engineering/Research/ibmfl
    staging_dir: /home/trevormaxjs/Documents/Engineering/Research
    venv_dir: /home/trevormaxjs/Documents/Engineering/Research/venv
    venv_uses_conda: 'false'
  keegdesk70:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8070
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk71:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8071
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk72:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8072
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk73:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8073
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk74:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8074
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk75:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8075
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk76:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8076
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk77:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8077
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk78:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8078
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk79:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8079
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk80:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8080
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk81:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8081
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk82:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8082
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk83:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8083
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk84:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8084
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk85:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8085
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk86:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8086
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk87:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8087
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk88:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8088
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  keegdesk89:
    ibmfl_dir: /home/mud/research/venv
    ip_address: 192.162.1.197
    port_number: 8089
    ssh_username: mud
    staging_dir: /home/mud/research/ibmfl
    venv_dir: /home/mud/research/
  local0:
    ip_address: 192.162.1.176
    port_number: 5000
    ssh_username: trevormaxjs
  popdesk0:
    ibmfl_dir: XXXXXX
    ip_address: 192.162.1.???
    port_number: 8000
    ssh_username: trevormaxjs
    staging_dir: XXXXXXXXXXXX
    venv_dir: XXXXXXXXX
  popdesk1:
    ibmfl_dir: XXXXXX
    ip_address: 192.162.1.???
    port_number: 8001
    ssh_username: trevormaxjs
    staging_dir: XXXXXXXXXXXX
    venv_dir: XXXXXXXXX
  popdesk2:
    ibmfl_dir: XXXXXX
    ip_address: 192.162.1.???
    port_number: 8002
    ssh_username: trevormaxjs
    staging_dir: XXXXXXXXXXXX
    venv_dir: XXXXXXXXX
  popdesk3:
    ibmfl_dir: XXXXXX
    ip_address: 192.162.1.???
    port_number: 8003
    ssh_username: trevormaxjs
    staging_dir: XXXXXXXXXXXX
    venv_dir: XXXXXXXXX
  popdesk4:
    ibmfl_dir: XXXXXX
    ip_address: 192.162.1.???
    port_number: 8004
    ssh_username: trevormaxjs
    staging_dir: XXXXXXXXXXXX
    venv_dir: XXXXXXXXX
  popdesk5:
    ibmfl_dir: XXXXXX
    ip_address: 192.162.1.???
    port_number: 8005
    ssh_username: trevormaxjs
    staging_dir: XXXXXXXXXXXX
    venv_dir: XXXXXXXXX
  popdesk6:
    ibmfl_dir: XXXXXX
    ip_address: 192.162.1.???
    port_number: 8006
    ssh_username: trevormaxjs
    staging_dir: XXXXXXXXXXXX
    venv_dir: XXXXXXXXX
  popdesk7:
    ibmfl_dir: XXXXXX
    ip_address: 192.162.1.???
    port_number: 8007
    ssh_username: trevormaxjs
    staging_dir: XXXXXXXXXXXX
    venv_dir: XXXXXXXXX
  popdesk8:
    ibmfl_dir: XXXXXX
    ip_address: 192.162.1.???
    port_number: 8008
    ssh_username: trevormaxjs
    staging_dir: XXXXXXXXXXXX
    venv_dir: XXXXXXXXX
  popdesk9:
    ibmfl_dir: XXXXXX
    ip_address: 192.162.1.???
    port_number: 8009
    ssh_username: trevormaxjs
    staging_dir: XXXXXXXXXXXX
    venv_dir: XXXXXXXXX
  schooltop50:
    ip_address: 192.162.1.176
    port_number: 8050
    ssh_username: trevormaxjs
  schooltop51:
    ip_address: 192.162.1.176
    port_number: 8051
    ssh_username: trevormaxjs
  schooltop52:
    ip_address: 192.162.1.176
    port_number: 8052
    ssh_username: trevormaxjs
  schooltop53:
    ip_address: 192.162.1.176
    port_number: 8053
    ssh_username: trevormaxjs
  schooltop54:
    ip_address: 192.162.1.176
    port_number: 8054
    ssh_username: trevormaxjs
  schooltop55:
    ip_address: 192.162.1.176
    port_number: 8055
    ssh_username: trevormaxjs
  schooltop56:
    ip_address: 192.162.1.176
    port_number: 8056
    ssh_username: trevormaxjs
  schooltop57:
    ip_address: 192.162.1.176
    port_number: 8057
    ssh_username: trevormaxjs
  schooltop58:
    ip_address: 192.162.1.176
    port_number: 8058
    ssh_username: trevormaxjs
  schooltop59:
    ip_address: 192.162.1.176
    port_number: 8059
    ssh_username: trevormaxjs
  schooltop60:
    ip_address: 192.162.1.176
    port_number: 8060
    ssh_username: trevormaxjs
  schooltop61:
    ip_address: 192.162.1.176
    port_number: 8061
    ssh_username: trevormaxjs
  schooltop62:
    ip_address: 192.162.1.176
    port_number: 8062
    ssh_username: trevormaxjs
  schooltop63:
    ip_address: 192.162.1.176
    port_number: 8063
    ssh_username: trevormaxjs
  schooltop64:
    ip_address: 192.162.1.176
    port_number: 8064
    ssh_username: trevormaxjs
  schooltop65:
    ip_address: 192.162.1.176
    port_number: 8065
    ssh_username: trevormaxjs
  schooltop66:
    ip_address: 192.162.1.176
    port_number: 8066
    ssh_username: trevormaxjs
  schooltop67:
    ip_address: 192.162.1.176
    port_number: 8067
    ssh_username: trevormaxjs
  schooltop68:
    ip_address: 192.162.1.176
    port_number: 8068
    ssh_username: trevormaxjs
  schooltop69:
    ip_address: 192.162.1.176
    port_number: 8069
    ssh_username: trevormaxjs
  worktop10:
    ip_address: 192.162.1.167
    port_number: 8010
    ssh_username: trevormaxjs
  worktop11:
    ip_address: 192.162.1.167
    port_number: 8011
    ssh_username: trevormaxjs
  worktop12:
    ip_address: 192.162.1.167
    port_number: 8012
    ssh_username: trevormaxjs
  worktop13:
    ip_address: 192.162.1.167
    port_number: 8013
    ssh_username: trevormaxjs
  worktop14:
    ip_address: 192.162.1.167
    port_number: 8014
    ssh_username: trevormaxjs
  worktop15:
    ip_address: 192.162.1.167
    port_number: 8015
    ssh_username: trevormaxjs
  worktop16:
    ip_address: 192.162.1.167
    port_number: 8016
    ssh_username: trevormaxjs
  worktop17:
    ip_address: 192.162.1.167
    port_number: 8017
    ssh_username: trevormaxjs
  worktop18:
    ip_address: 192.162.1.167
    port_number: 8018
    ssh_username: trevormaxjs
  worktop19:
    ip_address: 192.162.1.167
    port_number: 8019
    ssh_username: trevormaxjs
  worktop20:
    ip_address: 192.162.1.167
    port_number: 8020
    ssh_username: trevormaxjs
  worktop21:
    ip_address: 192.162.1.167
    port_number: 8021
    ssh_username: trevormaxjs
  worktop22:
    ip_address: 192.162.1.167
    port_number: 8022
    ssh_username: trevormaxjs
  worktop23:
    ip_address: 192.162.1.167
    port_number: 8023
    ssh_username: trevormaxjs
  worktop24:
    ip_address: 192.162.1.167
    port_number: 8024
    ssh_username: trevormaxjs
  worktop25:
    ip_address: 192.162.1.167
    port_number: 8025
    ssh_username: trevormaxjs
  worktop26:
    ip_address: 192.162.1.167
    port_number: 8026
    ssh_username: trevormaxjs
  worktop27:
    ip_address: 192.162.1.167
    port_number: 8027
    ssh_username: trevormaxjs
  worktop28:
    ip_address: 192.162.1.167
    port_number: 8028
    ssh_username: trevormaxjs
  worktop29:
    ip_address: 192.162.1.167
    port_number: 8029
    ssh_username: trevormaxjs
  worktop30:
    ip_address: 192.162.1.167
    port_number: 8030
    ssh_username: trevormaxjs
  worktop31:
    ip_address: 192.162.1.167
    port_number: 8031
    ssh_username: trevormaxjs
  worktop32:
    ip_address: 192.162.1.167
    port_number: 8032
    ssh_username: trevormaxjs
  worktop33:
    ip_address: 192.162.1.167
    port_number: 8033
    ssh_username: trevormaxjs
  worktop34:
    ip_address: 192.162.1.167
    port_number: 8034
    ssh_username: trevormaxjs
  worktop35:
    ip_address: 192.162.1.167
    port_number: 8035
    ssh_username: trevormaxjs
  worktop36:
    ip_address: 192.162.1.167
    port_number: 8036
    ssh_username: trevormaxjs
  worktop37:
    ip_address: 192.162.1.167
    port_number: 8037
    ssh_username: trevormaxjs
  worktop38:
    ip_address: 192.162.1.167
    port_number: 8038
    ssh_username: trevormaxjs
  worktop39:
    ip_address: 192.162.1.167
    port_number: 8039
    ssh_username: trevormaxjs
  worktop40:
    ip_address: 192.162.1.167
    port_number: 8040
    ssh_username: trevormaxjs
  worktop41:
    ip_address: 192.162.1.167
    port_number: 8041
    ssh_username: trevormaxjs
  worktop42:
    ip_address: 192.162.1.167
    port_number: 8042
    ssh_username: trevormaxjs
  worktop43:
    ip_address: 192.162.1.167
    port_number: 8043
    ssh_username: trevormaxjs
  worktop44:
    ip_address: 192.162.1.167
    port_number: 8044
    ssh_username: trevormaxjs
  worktop45:
    ip_address: 192.162.1.167
    port_number: 8045
    ssh_username: trevormaxjs
  worktop46:
    ip_address: 192.162.1.167
    port_number: 8046
    ssh_username: trevormaxjs
  worktop47:
    ip_address: 192.162.1.167
    port_number: 8047
    ssh_username: trevormaxjs
  worktop48:
    ip_address: 192.162.1.167
    port_number: 8048
    ssh_username: trevormaxjs
  worktop49:
    ip_address: 192.162.1.167
    port_number: 8049
    ssh_username: trevormaxjs
